"""Rename google_drive_id to source_file_id

Revision ID: e1b567ed9632
Revises: e7db294657c7
Create Date: 2025-12-24 13:30:48.246819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b567ed9632'
down_revision: Union[str, Sequence[str], None] = 'e7db294657c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('source_file_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_images_google_drive_id'), table_name='images')
    op.create_index(op.f('ix_images_source_file_id'), 'images', ['source_file_id'], unique=True)
    op.drop_column('images', 'google_drive_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('google_drive_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_images_source_file_id'), table_name='images')
    op.create_index(op.f('ix_images_google_drive_id'), 'images', ['google_drive_id'], unique=True)
    op.drop_column('images', 'source_file_id')
    # ### end Alembic commands ###
