"""Add source and status to images

Revision ID: e7db294657c7
Revises: 7706e78f2480
Create Date: 2025-12-24 12:33:45.464612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7db294657c7'
down_revision: Union[str, Sequence[str], None] = '7706e78f2480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('source', sa.String(), nullable=True))
    op.add_column('images', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_images_source'), 'images', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_source'), table_name='images')
    op.drop_column('images', 'status')
    op.drop_column('images', 'source')
    # ### end Alembic commands ###
